import type { Project } from '../types/projects.types';

/**
 * The project catalog. Prose lives in the i18n catalogs under
 * `projects.items.<slug>`; everything here is verifiable structure — names,
 * stacks, categories and links. A `live` URL is listed only after the URL was
 * confirmed to respond, and `repository` stays null for employer-owned systems
 * so nothing implies the source is public.
 */
export const PROJECTS: readonly Project[] = [
  {
    slug: 'clawai',
    name: 'ClawAI',
    kind: 'open-source',
    categories: ['ai', 'backend', 'fullstack', 'platforms', 'opensource'],
    stack: [
      'Next.js',
      'NestJS',
      'TypeScript',
      'Microservices',
      'PostgreSQL',
      'MongoDB',
      'Redis',
      'Ollama',
      'llama.cpp',
      'Docker',
    ],
    links: {
      repository: 'https://github.com/ihabkhaled/ClawAI',
      live: 'https://claw-frontend-five.vercel.app',
    },
    repositoryName: 'ClawAI',
    priority: 1,
    featured: true,
    hasCaseStudy: true,
    fallbackUpdatedAt: '2026-07-29',
  },
  {
    slug: 'auraspear',
    name: 'AuraSpear Platform',
    kind: 'open-source',
    categories: ['security', 'ai', 'backend', 'platforms', 'opensource'],
    stack: [
      'Next.js',
      'NestJS',
      'TypeScript',
      'Prisma',
      'PostgreSQL',
      'Redis',
      'OpenSearch',
      'Wazuh',
      'MISP',
      'AWS Bedrock',
      'Docker',
    ],
    links: {
      repository: 'https://github.com/ihabkhaled/auraspear-platform',
      live: null,
    },
    repositoryName: 'auraspear-platform',
    priority: 2,
    featured: true,
    hasCaseStudy: true,
    fallbackUpdatedAt: '2026-07-28',
  },
  {
    slug: 'foodorder',
    name: 'FoodOrderV1',
    kind: 'open-source',
    categories: ['mobile', 'fullstack', 'opensource'],
    stack: [
      'React',
      'TypeScript',
      'Vite',
      'Capacitor',
      'Firebase Authentication',
      'Cloud Firestore',
      'Playwright',
      'Android',
      'iOS',
    ],
    links: {
      repository: 'https://github.com/ihabkhaled/FoodOrderV1',
      live: 'https://food-order-v1-peach.vercel.app',
    },
    repositoryName: 'FoodOrderV1',
    priority: 3,
    featured: true,
    hasCaseStudy: true,
    fallbackUpdatedAt: '2026-07-27',
  },
  {
    slug: 'twinzyai',
    name: 'TwinzyAI',
    kind: 'open-source',
    categories: ['ai', 'mobile', 'fullstack', 'opensource'],
    stack: ['Next.js', 'NestJS', 'Fastify', 'TypeScript', 'Gemini', 'Docker'],
    links: {
      repository: 'https://github.com/ihabkhaled/TwinzyAI',
      live: null,
    },
    repositoryName: 'TwinzyAI',
    priority: 4,
    featured: true,
    hasCaseStudy: true,
    fallbackUpdatedAt: '2026-07-28',
  },
  {
    slug: 'nextranger',
    name: 'NextRanger',
    kind: 'open-source',
    categories: ['fullstack', 'platforms', 'opensource'],
    stack: ['Next.js', 'React', 'TypeScript', 'ESLint', 'Vitest', 'Playwright', 'Tailwind CSS'],
    links: {
      repository: 'https://github.com/ihabkhaled/NextRanger',
      live: null,
    },
    repositoryName: 'NextRanger',
    priority: 5,
    featured: true,
    hasCaseStudy: true,
    fallbackUpdatedAt: '2026-07-27',
  },
  {
    slug: 'myoncare',
    name: 'myoncare',
    kind: 'professional',
    categories: ['healthcare', 'backend', 'fullstack', 'integrations', 'mobile'],
    stack: [
      'Node.js',
      'NestJS',
      'TypeScript',
      'React',
      'React Native',
      'Capacitor',
      'MySQL',
      'MongoDB',
      'Redis',
      'RabbitMQ',
      'FHIR',
      'Docker',
    ],
    links: { repository: null, live: 'https://myoncare.com' },
    repositoryName: null,
    priority: 6,
    featured: false,
    hasCaseStudy: false,
    fallbackUpdatedAt: null,
  },
  {
    slug: 'garment-io',
    name: 'Garment IO',
    kind: 'professional',
    categories: ['backend', 'fullstack', 'integrations', 'platforms'],
    stack: [
      'Node.js',
      'PHP',
      'Laravel',
      'React',
      'MongoDB',
      'MySQL',
      'Redis',
      'Python',
      'Flask',
      'Nginx',
    ],
    links: { repository: null, live: 'https://garment.io' },
    repositoryName: null,
    priority: 7,
    featured: false,
    hasCaseStudy: false,
    fallbackUpdatedAt: null,
  },
  {
    slug: 'tarsyaa',
    name: 'Tarsyaa',
    kind: 'professional',
    categories: ['backend', 'fullstack', 'platforms'],
    stack: [
      'NestJS',
      'Node.js',
      'React',
      'Vite',
      'TypeScript',
      'TypeORM',
      'PostgreSQL',
      'Redis',
      'Docker',
    ],
    links: { repository: null, live: null },
    repositoryName: null,
    priority: 8,
    featured: false,
    hasCaseStudy: false,
    fallbackUpdatedAt: null,
  },
  {
    slug: 'ovarc',
    name: 'Ovarc',
    kind: 'professional',
    categories: ['backend', 'fullstack', 'platforms'],
    stack: ['React', 'Node.js', 'Sequelize', 'Prisma', 'MySQL', 'Docker'],
    links: { repository: null, live: 'https://ovarc.io' },
    repositoryName: null,
    priority: 9,
    featured: false,
    hasCaseStudy: false,
    fallbackUpdatedAt: null,
  },
  {
    slug: 'callrater',
    name: 'CallRater / Dealer-FX',
    kind: 'professional',
    categories: ['backend', 'fullstack'],
    stack: ['PHP', 'MySQL', 'Angular', 'JavaScript', 'Apache'],
    links: { repository: null, live: null },
    repositoryName: null,
    priority: 10,
    featured: false,
    hasCaseStudy: false,
    fallbackUpdatedAt: null,
  },
  {
    slug: 'vms',
    name: 'Volunteering Management System',
    kind: 'professional',
    categories: ['backend', 'fullstack'],
    stack: ['PHP', 'Laravel', 'MySQL', 'Eloquent', 'JavaScript', 'Apache'],
    links: { repository: null, live: null },
    repositoryName: null,
    priority: 11,
    featured: false,
    hasCaseStudy: false,
    fallbackUpdatedAt: null,
  },
  {
    slug: 'health-integrations',
    name: 'Health & Wearable Integrations',
    kind: 'professional',
    categories: ['integrations', 'healthcare', 'backend'],
    stack: [
      'FHIR',
      'Withings',
      'Apple Health',
      'Android Health Connect',
      'Node.js',
      'Swift',
      'Kotlin',
    ],
    links: { repository: null, live: null },
    repositoryName: null,
    priority: 12,
    featured: false,
    hasCaseStudy: false,
    fallbackUpdatedAt: null,
  },
  {
    slug: 'payment-integrations',
    name: 'Payment & Platform Integrations',
    kind: 'professional',
    categories: ['integrations', 'backend'],
    stack: ['Stripe', 'PayPal', 'Spotify API', 'NestJS', 'Node.js', 'PHP'],
    links: { repository: null, live: null },
    repositoryName: null,
    priority: 13,
    featured: false,
    hasCaseStudy: false,
    fallbackUpdatedAt: null,
  },
] as const;

/** Repositories whose live GitHub metadata is fetched, in editorial order. */
export const CURATED_REPOSITORY_NAMES: readonly string[] = PROJECTS.flatMap((project) =>
  project.repositoryName === null ? [] : [project.repositoryName],
);

/** Days within which a repository still counts as recently active. */
export const RECENT_ACTIVITY_DAYS = 120;
