import type { SkillTierGroup } from '../types/skills.types';

/**
 * Skills grouped by depth of production experience. No percentages: a tier is
 * a qualitative claim, and its definition (in the message catalog) is the
 * only thing that has to be honest, not a number.
 */
export const SKILL_TIER_GROUPS: readonly SkillTierGroup[] = [
  {
    tier: 'primary',
    technologies: [
      'JavaScript',
      'TypeScript',
      'Node.js',
      'NestJS',
      'Express.js',
      'React',
      'Next.js',
      'REST APIs',
      'Backend architecture',
      'Full-stack development',
      'Integrations',
      'Microservices',
      'System design',
      'Authentication & RBAC',
      'Production troubleshooting',
      'Docker',
      'Testing',
      'CI/CD',
      'Git',
    ],
  },
  {
    tier: 'strong',
    technologies: [
      'MySQL',
      'PostgreSQL',
      'MongoDB',
      'Redis',
      'RabbitMQ',
      'Firebase',
      'Sequelize',
      'Prisma',
      'TypeORM',
      'Mongoose',
      'React Native',
      'Capacitor',
      'Nginx',
      'Google Cloud Platform',
      'GitHub Actions',
      'Bitbucket Pipelines',
      'Unit & integration testing',
      'Security hardening',
      'Performance optimisation',
      'AI & LLM integrations',
      'Third-party API integrations',
    ],
  },
  {
    tier: 'working',
    technologies: [
      'PHP',
      'Laravel',
      'Python',
      'Flask',
      'C#',
      'WordPress',
      'Kubernetes',
      'Kotlin',
      'Swift',
      'Linux administration',
      'Shell & Bash',
      'Apache',
      'AWS',
      'Elasticsearch & OpenSearch',
      'Wazuh & security tooling',
    ],
  },
  {
    tier: 'foundational',
    technologies: [
      'Java & Spring Boot',
      'Go',
      'C++',
      'OpenGL',
      'Matlab',
      'Networking (CCNA)',
      'GraphQL',
      'Terraform',
      'Redux',
      'Vue.js',
      'macOS',
      'Windows',
      'Linux (Ubuntu)',
      'Linux (Fedora)',
      'Linux (CentOS)',
      'Linux (Kali)',
    ],
  },
  {
    tier: 'aiTools',
    technologies: [
      'Claude Code',
      'Claude Opus 4.6',
      'Claude Opus 4.7',
      'Claude Opus 4.8',
      'Claude Opus 5',
      'Claude Fable 5',
      'OpenAI Codex',
      'GPT-5.2',
      'GPT-5.3',
      'GPT-5.4',
      'GPT-5.5 Sol',
      'GPT-5.6 Luna',
      'GPT Terra',
      'Cursor',
      'Kimi K2.6',
      'Kimi K2.7',
      'Kimi K3',
    ],
  },
] as const;
