import type { ExperienceRole } from '../types/experience.types';

/**
 * Career history. Prose lives in the catalogs under `experience.roles.<id>`;
 * organisations, titles, dates and stacks are structural facts kept here.
 */
export const EXPERIENCE_ROLES: readonly ExperienceRole[] = [
  {
    id: 'oncare',
    organisation: 'Oncare GmbH',
    title: 'Senior Software Engineer — Full-Stack & Integrations',
    kind: 'employment',
    startedAt: '2022-06',
    endedAt: null,
    locationId: 'remote',
    website: 'https://myoncare.com',
    stack: [
      'Node.js',
      'NestJS',
      'Express.js',
      'TypeScript',
      'React',
      'React Native',
      'Capacitor',
      'MySQL',
      'MongoDB',
      'Redis',
      'RabbitMQ',
      'Docker',
      'FHIR',
      'Kotlin',
      'Swift',
    ],
    highlightKeys: ['one', 'two', 'three', 'four', 'five'],
  },
  {
    id: 'garment',
    organisation: 'Garment IO',
    title: 'Software & Integration Engineer',
    kind: 'employment',
    startedAt: '2018-12',
    endedAt: '2022-06',
    locationId: 'remote',
    website: 'https://garment.io',
    stack: [
      'Node.js',
      'PHP',
      'Laravel',
      'React',
      'MongoDB',
      'MySQL',
      'Redis',
      'Python',
      'Flask',
      'Docker',
      'CentOS',
    ],
    highlightKeys: ['one', 'two', 'three', 'four', 'five'],
  },
  {
    id: 'eseed',
    organisation: 'eSEED',
    title: 'Software & Integration Engineer',
    kind: 'employment',
    startedAt: '2018-12',
    endedAt: '2022-06',
    locationId: 'egypt',
    website: 'https://eseed.net',
    stack: [
      'JavaScript',
      'React',
      'Node.js',
      'Spring Boot',
      'MySQL',
      'HTML5',
      'CSS',
      'Bootstrap',
      'jQuery',
      'WordPress',
    ],
    highlightKeys: ['one', 'two', 'three', 'four'],
  },
  {
    id: 'freelance',
    organisation: 'Independent',
    title: 'Software & Integration Engineer',
    kind: 'independent',
    startedAt: '2016-06',
    endedAt: null,
    locationId: 'egypt',
    website: null,
    stack: [
      'TypeScript',
      'Node.js',
      'NestJS',
      'Next.js',
      'React',
      'React Native',
      'PostgreSQL',
      'MySQL',
      'MongoDB',
      'Redis',
      'Docker',
      'GCP',
      'CI/CD',
    ],
    highlightKeys: ['one', 'two', 'three', 'four', 'five', 'six'],
  },
] as const;
